### ISSUE TITLE
PythonDirectoryReadme.md doesn't show

### ISSUE THREAD

**Issue by danmaps** [RachelG-GIS/shared-resources#6]
It looks like it has to be named "README.md" in order to work as expected!

**Comment by danmaps** [comment]
Fixed by #7. @RachelG-GIS you can merge this if you want! 👍

**Comment by danmaps** [comment]
You might want to organize your stuff more like this: https://github.com/Esri/developer-support/tree/master/python

There's a folder for each solution with a different readme.md in each folder. ✊

**Comment by RachelG-GIS** [comment]
Thanks for the help! I merged in your change. I'm going to be pondering organization a bit more :)
